// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLcBlcNfnG3zzdpOEC7RpJS3-WVKSECms',
    appId: '1:75987232461:web:d323213994407f5cce2b84',
    messagingSenderId: '75987232461',
    projectId: 'weatherapp-936df',
    authDomain: 'weatherapp-936df.firebaseapp.com',
    storageBucket: 'weatherapp-936df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE82SiLWznuzBNLbTybQ10mHOCQ5JDCcc',
    appId: '1:75987232461:android:50b6e2c734939af9ce2b84',
    messagingSenderId: '75987232461',
    projectId: 'weatherapp-936df',
    storageBucket: 'weatherapp-936df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5c3ZlRiHcKSS-k4NPtavJWfog8t0pqac',
    appId: '1:75987232461:ios:1bc2ddcaa1a75490ce2b84',
    messagingSenderId: '75987232461',
    projectId: 'weatherapp-936df',
    storageBucket: 'weatherapp-936df.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5c3ZlRiHcKSS-k4NPtavJWfog8t0pqac',
    appId: '1:75987232461:ios:1bc2ddcaa1a75490ce2b84',
    messagingSenderId: '75987232461',
    projectId: 'weatherapp-936df',
    storageBucket: 'weatherapp-936df.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLcBlcNfnG3zzdpOEC7RpJS3-WVKSECms',
    appId: '1:75987232461:web:b72ab1a9cbfbb6fece2b84',
    messagingSenderId: '75987232461',
    projectId: 'weatherapp-936df',
    authDomain: 'weatherapp-936df.firebaseapp.com',
    storageBucket: 'weatherapp-936df.firebasestorage.app',
  );
}
